POST https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auctions

{
    "title": "New Auction 1"
}


###
GET https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auctions

###
GET https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auction/d3db964b-a3a6-4436-a40c-99d36cb3ed04

###

PATCH https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auction/d3db964b-a3a6-4436-a40c-99d36cb3ed04/bid
Content-Type: application/json

{
    "amount": 20
}
