POST https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auctions

{
    "title": "New Auction"
}


###
GET https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auctions

###
GET https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auction/083349d0-4878-4c32-afdc-c30931a00a13
