POST https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auctions

{
    "title": "New Auction 3"
}


###
GET https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auctions

###
GET https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auction/d633eb82-11f4-4771-8156-2a5ddea2a343

###

PATCH https://g2edc10u4d.execute-api.us-east-1.amazonaws.com/dev/auction/d633eb82-11f4-4771-8156-2a5ddea2a343/bid
Content-Type: application/json

{
    "amount": 30
}
